   [build]
     base    = "frontend-angular"
     command = "npm run build"
     publish = "dist/frontend-angular/browser"

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200
